INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('4617','0','0','Stress de primavera');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('77577','1','1','El grito del sur. Casas Viejas');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','12','(#5.12)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','4','Buscando un Valium desesperadamente');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','8','Buscarse la vida');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','4','Besame, Alicia');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','6','2','Cara de angel');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','3','Caido del cielo');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','9','Cita a ciegas');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','2','Comunicando');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','8','Confidencias');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','2','Cosa Nostra');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','13','Deseo, pasion y paciencia');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','5','El fin del milenio');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','6','El guateque');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','7','El secreto del exito');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','11','Ellos y ella');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','3','1','Eligeme');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','8','Enamorados');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','4','Esta niña es mia');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','9','Esta tia es una hermana');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','12','Esto es la guerra');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','1','Gimnasia y amnesia');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','13','La quimera del oro');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','4','La tentacion vive abajo');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','11','La visita');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','6','Lecciones intimas');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','5','Los amigos de los niños');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','4','3','Madam Alicia');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','6','1','Malas influencias');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','11','Mama sale todas las noches');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','3','3','Mama, papa... y la novia de papa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','5','Margarita se llama mi amor');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','5','No me maltrates');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','7','Nimeros rojos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','6','Padre no hay mas que muchos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','2','Papeles');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','7','Pequeño tirano');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','6','Petri woman');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','9','Predicando en el desierto');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','1','Revista de tropa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','10','Seis en un sofa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','3','4','Semana de pasion');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','10','Ser padres');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','1','12','Temor y temblor');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','13','Terapia de contacto');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','2','10','Una chica natural');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('196397','5','3','Valiente San Valentin');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('227652','1','2','El senyor Josep enganya a la dona i la dona del senyor Josep falta a lhome');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('227652','1','4','Santiago Rusiñol: la vida');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('276971','0','0','Adolphe et les menteuses');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('276971','0','0','Martingale');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('276971','0','0','Rendez-vous à Lisbonne');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('276971','0','0','Retour');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('288125','0','0','Ópera en Marineda');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('300494','2','9','Instant Replay');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('300494','2','16','Venus Flytrap');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('325339','1','13','Parpados');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('325339','1','10','Un instante en tu piel');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('350673','0','0','(1986-02-10)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('438552','0','0','El vuelo de la cometa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('440544','4','1','Shanghai Lilly');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('489705','2','3','La zapatera prodigiosa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('495049','0','0','Damunt lherba');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('515016','0','0','Tots els que cauen');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('531596','0','0','Albert i Francina');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('531596','0','0','El Cafè de la Marina');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('531596','0','0','La nau');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('531596','0','0','La roda de la fortuna');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('573562','0','0','Mnemos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('573656','3','3','El fin empezo ayer');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','Ball robat');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','El Tartuf');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','El veri del teatre');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','Homes i no');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','La llotja');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','Molt soroll per no res');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','Revolta de bruixes');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','Salome');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('776601','0','0','Silvia Ocampo');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('810963','1','1','En el barrio sobra siensia y lo que farta se inventa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','1','(#1.1)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','10','(#1.10)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','2','(#1.2)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','3','(#1.3)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','4','(#1.4)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','6','(#1.6)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','8','(#1.8)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','9','(#1.9)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','16','(#2.16)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','22','(#2.22)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','4','(#2.4)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','5','(#2.5)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-06-12)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-06-19)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-09-25)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-10-02)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-10-23)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-11-13)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-11-20)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-11-27)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-12-11)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','(1997-12-25)');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','A toda pastilla');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','Acusado');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','8','Al pan, pan');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','Borriquito como tu');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','13','Besame mucho');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','1','Castillos en el aire');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','2','Cincuenta tacos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','Con nueve basta');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','20','Cosas de crios');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','23','Cria cuervos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','14','Dime que me quieres');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','3','1','El hombre del traje gris');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','El niño del Pellizquito');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','12','El que se fue a Sevilla');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','Expediente F');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','11','Fuimos novios');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','5','Haciendo trampas');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','3','6','Hogar, dulce hogar');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','3','4','La abuela cumple 80 años');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','La guerra del taxi');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','10','La sombra de una duda');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','6','La vida sigue igual');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','La ultima carrera');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','9','Las chicas son guerreras');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','17','Llamando a las puertas del cielo');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','19','Los niños no vienen de Paris');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','3','Madre no hay mas que dos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','3','3','Pareja de ases');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','7','Rebelde con causa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','3','2','Regalo de pedida');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','21','Sin perdon');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','Sucedio una noche');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','7','Tres meses y un dia');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','1','11','Tres no son multitud');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','18','Un tranvia llamado deseo');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','2','15','Y se armo el Belen');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','Ya esta aqui, ya llego');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','3','5','¡Fuego!');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('839229','0','0','¡Que noche la de aquel fin de año!');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('924681','1','7','Mes fort que la vida mateixa');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('925576','0','0','El camino I');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('926089','0','0','Elisabeth i Maria');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('980572','0','0','Alla ricerca di Sheherazade');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('980572','0','0','El hermano pequeño');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('980572','0','0','Il centravanti è stato assassinato verso sera');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('980572','0','0','La solitude du manager');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('980572','0','0','Padre, patron');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('980572','0','0','Tal como eramos');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1110798','1','3','La sombra del delator');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1145329','1','1','Sonata de primavera');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','6','Das Automobil');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','5','Der Salonlöwe');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','3','Die Braut');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','1','Die Geburt');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','7','Die Hochzeit');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','2','Die Renovierung');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1229042','1','4','Die Wiege');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1493539','0','0','Caramboles');
INSERT INTO Capitulo(idProduccion, idTemporada,idCapitulo, nombreCap) VALUES ('1584273','0','0','La opinion de Amy');
